### PR TITLE
Save users from trolling

### LINKED ISSUE #172: FastbootHeaders.get trolled me hard.
This is me whining, but I thought that if I got trolled so hard by such a subtle thing, other might be and it could be a way of mitigating it.

A coworker of mine made this change in an ember-data adapter:

```diff
          // Check that the returned data is of the expected format
 -        let headers = this.get('fastboot.request.headers');
 -        let contentType = headers.get('Content-Type');
 +        let headers = get(this, 'fastboot.request.headers');
 +        let contentType = get(headers, 'Content-Type');
```

By all means this seemed like a very reasonable code, it passed the review and got merged.

However, despite of what its so engrained in the mind of any Ember developer, `headers.get(key)` and `get(headers, key)` are not equivalent in this context.
See https://github.com/ember-fastboot/fastboot/blob/bb63049c5e529b9af4794ec1b0e592b7f32a47f8/src/fastboot-headers.js#L52-L54

If there is a way we could prevent other developers to pull their hair, I'd be happy to help

### PR DESCRIPTION
**Pull request by cibernox**
Closes #172 

/cc @danmcclain @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
@kratiahuja - Do you mind releasing (I can't get to it until tomorrow or Sunday)?

**Comment by kratiahuja** [comment]
@rwjblue Sure, I'll do in an hour or two. I'll ping on this PR once the new version is out and go ahead bump other deps.

**Comment by cibernox** [comment]
FWIW, this is not a pressing matter for me, no rush.

**Comment by kratiahuja** [comment]
`fastboot@1.1.1` is published.

**Pull request merged**
